# Generated by Django 3.0.5 on 2021-01-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'email_template',
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Saved'), (1, 'Sent')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=128)),
                ('from_name', models.CharField(max_length=64)),
                ('from_mail', models.CharField(max_length=64)),
                ('reply_mail', models.CharField(max_length=64)),
                ('reply_name', models.CharField(max_length=64)),
                ('email_to', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaign.EmailTemplate')),
            ],
            options={
                'db_table': 'email_campaign',
            },
        ),
    ]
